- name: Menyambungkan Koneksi Ke Remote Host
  hosts: "{{ hosts }}"
  gather_facts: true
  remote_user: root

  tasks:
   - name: Membuat Direktori Source CMS WordPress
     file: path=/opt/source state=directory mode=0775

   - name: Mengunduh File Master CMS WordPress
     get_url: url=https://www.wordpress.org/latest.tar.gz dest=/opt/source/wordpress.tar.gz validate_certs=no

   - name: Mengekstrak File Master CMS WordPress
     shell: tar -zxvf /opt/source/wordpress.tar.gz -C /var/www && mv /var/www/wordpress /var/www/html
    
   - name: Menyalin File Konfigurasi Sampel CMS WordPress
     copy: src=/opt/ansible-httpd-wordpress-mariadb-remotely/wp-config-sample.php dest=/var/www/html/wp-config.php mode=0644
